### ISSUE TITLE
Failed to build.

### ISSUE THREAD

**Issue by Teosis** [laurenth-unity/lightmap-switching-tool#17]
Good day! I'm getting this error when trying to build the scene: 

 LightsBakingSettings.cs(15,14): error CS1061: Type `UnityEngine.Light' does not contain a definition for `lightmapBakeType' and no extension method `lightmapBakeType' of type `UnityEngine.Light' could be found.

 How to get around this issue? 
 (Unity 2017.3.0f3)

**Comment by BANZBOWINKEL** [comment]
Hey, I disabled the script and it worked.
I am quite a noob though if it comes to programming and cannot judge if I harmed anything.
But it did the trick for me...

**Comment by laurenth-unity** [comment]
Hi, thanks for letting me know. The "lightmapBakeType" is indeed an editor only data so I should add a #if UNITY_EDITOR before this line. I'll do that and close this issue when it's fixed.
Commenting the line might work in some cases but probably breaks some features.

**Comment by laurenth-unity** [comment]
So I looked it up and indeed this file "LightsBakingSettings" was a test and isn't doing anything in its current state so it can be completely deleted. I'll delete it from the repo soon.

**Comment by laurenth-unity** [comment]
This should be fixed in the latest version. Thanks for reporting it :)
