### ISSUE TITLE
Unable to load lightmaps in Build; working fine in Editor

### ISSUE THREAD

**Issue by petergraham003** [laurenth-unity/lightmap-switching-tool#18]
Hi Laurenth,

I have built couple of scenes and baked as per steps provided. They seem to work fine in the Editor. However, when I build the project and test the same, lightmaps are not being loaded while switching from one scene to another.

**Comment by laurenth-unity** [comment]
Hi @petergraham003, I have built my little example project using unity 2017.3f1 on windows and things worked as expected. Could you provide more info or better provide an example ?

**Comment by katnyan** [comment]
Hi Laurenth,
I am able to solve this issue. It was my bad that I had broke the link to prefab instance after baking the light. However, this was working in the Editor somehow, but unable to load lightmaps in the build.

All I did was applied the changes on the Prefab and baked the Scene again and it worked !!! Thank You.. :-)

**Comment by petergraham003** [comment]
Hi Laurenth,
I am able to resolve this issue. It was my bad that I had broke the prefab instance after baking the light. It seems to work somehow in the Editor, but was not loading the lightmaps in the build. All I did was to apply the changes done to the Prefab and bake the light again. It worked!!! Thank You :-)
