### ISSUE TITLE
License and Usage

### ISSUE THREAD

**Issue by YoHann1992** [laurenth-unity/lightmap-switching-tool#20]
Hi there!

I've stumbled upon this repository and it is quite useful! Are you happy for this to be re-used in a product for commercial purposes?

If you are happy for us to use as is, could you possibly add a MIT license to the repository?

Here's a reference: https://help.github.com/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository

And a reference for an MIT license: https://choosealicense.com/licenses/mit/

Thanks!

**Comment by laurenth-unity** [comment]
Here you go, I'm happy if this is useful in any way :) and I wouldn't mind seing the result

**Comment by YoHann1992** [comment]
Hello again!

Thanks for that, that was really quick on your part!
Apologies for the late response on my end, though. :)

We decided to use additive scene loading as our final solution as we didn't want the base scene blocked, unfortunately. :/

I will probably end up using this for my personal projects tho! ^-^

Thanks again! :)
