### ISSUE TITLE
Static Geometry lightmaps missing

### ISSUE THREAD

**Issue by Gustorvo** [laurenth-unity/lightmap-switching-tool#23]
In your example project you have StaticGeometry folder with pre-baked maps, but in  your instructions you don't mention when I suppsoe to bake the Static Geometry scene. I wasn't able to reproduce map switching becouse I don't know at what step I am suppose to bake the static geometry scene.

**Comment by laurenth-unity** [comment]
The step that says "One by one, you can now Build the lighting scenario, and when the bake is done Store it. You need to do these steps in the lighting scenario order ( you cannot build and store lighting scenario 2 before lighting scenario 1 )." is the baking part of the instructions. I wrote "Build" but in this case it "bakes" or "generates lighting" as the UI says nowadays in unity

**Comment by laurenth-unity** [comment]
Using the build button loads the lighting scene and launches a bake for you
